need to fix line 176 of data_taker
  File "D:\GitHub\dielectric_spectroscopy_GPIB\data_taker.py", line 342, in <module>
    main_window = PlotWindow(sys.argv)
                  ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\dielectric_spectroscopy_GPIB\data_taker.py", line 30, in __init__
    self.plot_widget = PlotWidget(sys_argv)
                       ^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\dielectric_spectroscopy_GPIB\data_taker.py", line 176, in __init__
    self.frequencies = [int(f) for f in sys_argv[3].split(",")]
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\GitHub\dielectric_spectroscopy_GPIB\data_taker.py", line 176, in <listcomp>
    self.frequencies = [int(f) for f in sys_argv[3].split(",")]
                        ^^^^^^
ValueError: invalid literal for int() with base 10: 'Drive\\Dielectric_data'